# docker-compose.yml

version: '1'

services:
  app-server:
    build: .
    image: youtube-app
    links:
      - mongo
    volumes:
      - ./:/application

  mongodb:
    image: mongo
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=youtube-trends
    volumes:
      - ./tmp/db:/var/lib/mongo

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    links:
      - blog-server